apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  namespace: {{ include "elasticsearch.name" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "elasticsearch.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "elasticsearch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "elasticsearch.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }} 
      {{- end }}
      serviceAccountName: {{ include "elasticsearch.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes: 
        - name: {{ include "elasticsearch.fullname" . }}-storage
          {{- if .Values.persistentVolumeClaim.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "elasticsearch.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      initContainers:
        - name: increase-the-vm-max-map-count
          image: busybox
          command:
          - sysctl
          - -w
          - vm.max_map_count=262144
          securityContext:
            privileged: true
        - name: increase-the-ulimit
          image: busybox
          command:
          - sh
          - -c
          - ulimit -n 65536
          securityContext:
            privileged: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: network.host
              value: "_site_"
            - name: node.name
              value: "${HOSTNAME}"
            - name: bootstrap_memory_lock
              value: "true"
            - name: discovery.type
              value: {{ .Values.discoveryType | quote }}
            - name: ES_JAVA_OPTS
              value: {{ .Values.javaOpts | quote }}
            - name: cluster.name
              value: "{{ include "elasticsearch.name" . }}"
            {{- list .Values.xpack "xpack" | include "recurseFlattenMap" | trim | nindent 12 }}
            {{- if eq .Values.discoveryType "cluster" }}
            - name: discovery.zen.ping.unicast.hosts
              value: {{ include "elasticsearch.masterHosts" . }}
            {{- if has "master" .Values.nodeType }}
            - name: discovery.zen.minimum_master_nodes
              value: {{ add (div .Values.replicaCount 2 | floor) 1 | quote }}
            {{- end }}
            - name: node.master
              value: "{{ has "master" .Values.nodeType }}"
            - name: node.data
              value: "{{ has "data" .Values.nodeType }}"
            - name: node.ingest
              value: "{{ has "ingest" .Values.nodeType }}"
            {{- end }}
          volumeMounts:
            - name: {{ include "elasticsearch.fullname" . }}-storage
              mountPath: /usr/share/elasticsearch/data
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: tcp
              containerPort: 9300
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 9200
          readinessProbe:
            httpGet:
              path: /
              port: 9200
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
