apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  namespace: {{ include "elasticsearch.name" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentVolumeClaim.storageClass | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storageRequest }}
