apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  namespace: {{ include "elasticsearch.name" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.tcpPort }}
      targetPort: {{ .Values.service.tcpPort }}
      protocol: TCP
      name: tcp
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
