# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: test

replicaCount: 3

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 5.6.16

# support: single-node, cluster
discoveryType: cluster
nodeType:
  - master
  - data
  - ingest

javaOpts: "-Xms1g -Xmx2g"

xpack:
  security:
    enabled: false
  monitoring:
    enabled: false

serviceAccount:
  create: true
  annotations: {}
  name: "elasticsearch"

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

service:
  type: ClusterIP
  httpPort: 9200
  tcpPort: 9300

ingress:
  enabled: false

resources:
  requests:
    cpu: 500m
    memory: 1Gi

persistentVolumeClaim:
  # support: local-storage, aws-gp2, longhorn
  enabled: false
  storageClass: "local-storage"
  storageRequest: 5Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
