# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: test

version: 5.6.16

# support: single-node, cluster
discoveryType: cluster

# support: local-storage, aws-gp2, longhorn or empty
storageClass: ""

nodeSets:
  - name: master-nodes
    count: 3
    roles:
      - master
    javaOpts: "-Xms2g -Xmx2g"
    resources:
      limits:
        cpu: 1
        memory: 4Gi
    volumeClaim:
      storageRequest: 5Gi
  # - name: data-nodes
  #   count: 2
  #   roles:
  #     - data
  #     - ingest
  #   javaOpts: "-Xms2g -Xmx2g"
  #   resources:
  #     limits:
  #       cpu: 1
  #       memory: 4Gi
  #   volumeClaim:
  #     storageRequest: 5Gi

xpack:
  security:
    enabled: false
  monitoring:
    enabled: false

plugins:
  - analysis-phonetic
  - analysis-icu
  - analysis-kuromoji
  - repository-s3

podSecurityContext:
  fsGroup: 1000

securityContext: {}

service:
  type: ClusterIP
  httpPort: 9200
  tcpPort: 9300

serviceAccount:
  create: true

ingress:
  enabled: false
