# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: test

version: 7.15.2

# support: single-node, cluster
discoveryType: cluster

# support: local-storage, aws-gp2, longhorn or empty
storageClass: ""

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 300
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

nodeSets:
  - name: master-nodes
    count: 1
    roles:
      - master
    javaOpts: "-Xms2g -Xmx2g"
    resources:
      limits:
        cpu: 1
        memory: 4Gi
    volumeClaim:
      storageRequest: 5Gi
  - name: data-nodes
    count: 2
    roles:
      - data
      - ingest
    javaOpts: "-Xms2g -Xmx2g"
    resources:
      limits:
        cpu: 1
        memory: 4Gi
    volumeClaim:
      storageRequest: 5Gi

plugins:
  - analysis-phonetic
  - analysis-icu
  - analysis-kuromoji
  - repository-s3
